# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

In [2]:
a = np.zeros((3,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [13]:
x=np.diag(np.arange(4)+1,k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
x = np.zeros((8,8),dtype=int)

x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [23]:
a = np.random.random((5,5))
amax, amin = a.max(), a.min()
a= (a-amin)/(amax-amin)
print (a)

[[0.56369729 0.95766712 0.56344589 0.87639078 0.40989422]
 [0.96925673 0.82616615 0.6973005  0.         0.31988942]
 [0.57492935 0.7813057  0.75932589 0.1904262  1.        ]
 [0.14413979 0.16491498 0.23064655 0.02391958 0.59632619]
 [0.73115496 0.0702252  0.83727622 0.99158318 0.05829999]]


# 5.  How to find common values between two arrays?

In [32]:
x = np.array([0, 10, 2, 4, 6])
print("x=",array)
y = [10, 3, 4]
print("y=",array1)
print("Common values between two arrays are:")
print(np.intersect1d(x, y))

x= [ 0 10  2  4  6]
y= [10, 3, 4]
Common values between two arrays are:
[ 4 10]


# 6.How to get the dates of yesterday, today and tomorrow?

In [34]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday was : ",yesterday)
today     = np.datetime64('today', 'D')
print("Today is : ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow will  be: ",tomorrow)


Yestraday was :  2020-07-26
Today is :  2020-07-27
Tomorrow will  be:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [37]:
x1 = np.random.randint(0,2,6)
print("x1= ",x1)

y1 = np.random.randint(0,2,6)
print("y1=",y1)

print("Test ")
array_equal = np.allclose(x1, y1)
print(array_equal)


x1=  [1 1 1 1 0 0]
y1= [0 0 1 1 1 0]
Test 
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [39]:
x = np.array([0, 10, 2, 4, 6])
print("x= ",x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:",x)


x=  [ 0 10  2  4  6]
Maximum value replaced by 0: [0 0 2 4 6]


# 9. How to print all the values of an array?

In [43]:

x = np.zeros((4, 4))
print(x)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [46]:
import numpy as np
print("x= \n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y =  X - X.mean(axis=1,  keepdims=True)
print(Y)


x= 

[[0.17486386 0.64218135 0.55746575 0.43909169 0.52909322 0.29355087
  0.00957702 0.91160222 0.65454588 0.80074857]
 [0.95584744 0.12468222 0.70675716 0.12409448 0.98695591 0.72474998
  0.08145093 0.51515163 0.81497465 0.2274811 ]
 [0.09294256 0.0132496  0.66761674 0.4290222  0.41874488 0.09448433
  0.69787048 0.66203152 0.19152019 0.68170324]
 [0.61660759 0.51640874 0.22356725 0.69764625 0.42083727 0.36038465
  0.18127611 0.33537298 0.32363332 0.63931294]
 [0.96329224 0.23122458 0.51981296 0.01952012 0.06234474 0.22692318
  0.51522358 0.55788696 0.44541493 0.15351003]]

Subtract the mean of each row of the said matrix:

[[-0.32640818  0.14090931  0.0561937  -0.06218035  0.02782118 -0.20772117
  -0.49169503  0.41033018  0.15327384  0.29947652]
 [ 0.42963289 -0.40153233  0.18054261 -0.40212007  0.46074136  0.19853543
  -0.44476362 -0.01106292  0.2887601  -0.29873345]
 [-0.30197601 -0.38166898  0.27269816  0.03410362  0.02382631 -0.30043425
   0.30295191  0.26711295 -0.20339838  0.28

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [70]:
Z = np.ones(10)
print("Z=",Z)
A = np.random.randint(0,len(Z),20)
Z += np.bincount(A, minlength=len(Z))
print("Sol.:",Z)

Z= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Sol.: [2. 5. 1. 4. 2. 1. 3. 4. 5. 3.]


# 12.How to get the diagonal of a dot product?

In [71]:
x = np.random.uniform(0,2,(3,3))
y = np.random.uniform(0,2,(3,3))
s=np.diag(np.dot(x,y))
print("dot product is=",s)

dot product is= [3.95741096 4.50397316 2.03632232]



# 13.How to find the most frequent value in an array?

In [74]:
a = np.random.randint(0,10,20)
print("a=",a)
print("most frequent value=",np.bincount(a).argmax())

a= [8 2 5 2 1 7 2 7 7 9 0 9 3 8 6 9 2 4 2 1]
most frequent value= 2


# 14.How to get the n largest values of an array

In [84]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [87]:
a = np.array([("Iron man", 88.5, 90),
                 ("Captain", 87, 99),
             ("Thor", 85.5, 91)])
print("a= ",a)
print("\nRecord array;")
result = np.core.records.fromarrays(a.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

a=  [['Iron man' '88.5' '90']
 ['Captain' '87' '99']
 ['Thor' '85.5' '91']]

Record array;
[(b'Iron man', 88.5, 90) (b'Captain', 87. , 99) (b'Thor', 85.5, 91)]
